// Guard that keeps Claude session, thread and project links off GitHub
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync, spawnSync } = require('child_process');
const { findLinks, scrub } = require('../scripts/claude-link-guard.cjs');

const ROOT = path.join(__dirname, '..');
const GUARD = path.join(ROOT, 'scripts/claude-link-guard.cjs');
// Built from parts so this file never contains a real link
const HOST = 'claude' + '.ai';
const SESSION = `https://${HOST}/code/session_0123abc`;
const PROJECT = `https://${HOST}/code/project/chan_1?thread=cmsg_2`;
const TRAILER = 'Claude' + '-Session: ' + SESSION;
const MARKER = '<!-- claude' + '-projects-attribution: {"github_login":"someone"} -->';

function run(args, input) {
  return spawnSync('node', [GUARD, ...args], { cwd: ROOT, input, encoding: 'utf8' });
}

test('detects session, project and bare links, trailers and the attribution marker', () => {
  expect(findLinks(`see ${SESSION}`)).toHaveLength(1);
  expect(findLinks(`[thread](${PROJECT})`)).toHaveLength(1);
  expect(findLinks(`${HOST}/code`)).toHaveLength(1);
  expect(findLinks(`fix\n\n${TRAILER}\n`)).toHaveLength(1);
  expect(findLinks(MARKER)).toHaveLength(1);
  expect(findLinks('Generated with [Claude Code](https://claude.com/claude-code)')).toHaveLength(0);
  expect(findLinks('Co-Authored-By: Claude <noreply@anthropic.com>')).toHaveLength(0);
});

test('catches links with no path, a query, a subdomain or URL encoding, but not prose', () => {
  expect(findLinks(`https://${HOST}`)).toHaveLength(1);
  expect(findLinks(`https://${HOST}?q=1`)).toHaveLength(1);
  expect(findLinks(`https://code.${HOST}/x`)).toHaveLength(1);
  expect(findLinks(`www.${HOST}`)).toHaveLength(1);
  expect(findLinks(`go=https%3A%2F%2F${HOST}%2Fcode`)).toHaveLength(1);
  expect(findLinks(`any URL on the ${HOST} domain`)).toHaveLength(0);
  expect(findLinks(`non${HOST}/foo`)).toHaveLength(0);
});

test('scrub leaves no stray pieces and keeps required fields non-empty', () => {
  const titled = scrub(`see [a](${SESSION} 'title') now`);
  expect(titled).toBe('see a now');
  expect(scrub(`intro\n\n[1]: ${SESSION}\n`)).toBe('intro\n');
  expect(scrub(`Done.\r\n\r\n\r\n${SESSION}\r\n`)).toBe('Done.\n');
  expect(findLinks(scrub(`x https://code.${HOST}/y z`))).toHaveLength(0);
  expect(scrub(`x https://code.${HOST}/y z`)).toBe('x  z');
  // The review bot's "Fix this" links carry parentheses inside the query
  const fixThis = `low risk.\n\n[Fix this →](https://${HOST}/code?q=regexes%20(around%20lines%2018-26)%20slash%20(x)&repo=a/b)\n`;
  expect(scrub(fixThis)).toBe('low risk.\n');
  expect(scrub(`see (https://${HOST}/code) here`)).toBe('see () here');
});

test('pre-push copes with a remote tip that was never fetched', () => {
  const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
  const result = run(['pre-push'], `refs/heads/x ${head} refs/heads/x ${'1'.repeat(40)}\n`);
  expect(result.stderr).not.toContain('fatal');
});

test('scrub removes the attribution block and session lines but keeps the rest', () => {
  const body = [
    MARKER,
    `_Requested by **lazy** · [project thread](${PROJECT})_`,
    '',
    'Before: something. After: something better.',
    '',
    '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
    '',
    SESSION,
    '',
    `[Fix this →](https://${HOST}/code?q=do%20it)`,
    `_Generated by [Claude Code](https://${HOST}/code)_`,
  ].join('\n');
  const clean = scrub(body);
  expect(findLinks(clean)).toHaveLength(0);
  expect(clean).toContain('Before: something. After: something better.');
  expect(clean).toContain('Generated with [Claude Code](https://claude.com/claude-code)');
  expect(clean).toContain('_Generated by Claude Code_');
  expect(clean).not.toContain('Requested by');
  expect(clean).not.toContain('Fix this');
  expect(scrub('nothing to see')).toBe('nothing to see');
});

test('commit-msg check rejects a session trailer and accepts a clean message', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'guard-'));
  const bad = path.join(dir, 'bad');
  const good = path.join(dir, 'good');
  fs.writeFileSync(bad, `Fix thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n${TRAILER}\n`);
  fs.writeFileSync(good, 'Fix thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n');
  expect(run(['check-msg', bad]).status).toBe(1);
  expect(run(['check-msg', good]).status).toBe(0);
});

test('Claude Code hook blocks publishing a link and allows everything else', () => {
  const pr = { tool_name: 'mcp__github__create_pull_request', tool_input: { body: `Done\n\n${SESSION}` } };
  const commit = { tool_name: 'Bash', tool_input: { command: `git commit -m "x\n\n${TRAILER}"` } };
  const push = { tool_name: 'Bash', tool_input: { command: `cd repo && git -C . commit -m "x ${SESSION}"` } };
  const search = { tool_name: 'Bash', tool_input: { command: `grep -r ${HOST}/ .` } };
  expect(run(['claude-hook'], JSON.stringify(push)).status).toBe(2);
  const bodyFile = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'guard-')), 'pr body.md');
  fs.writeFileSync(bodyFile, `Done\n\n${SESSION}\n`);
  const viaFile = { tool_name: 'Bash', tool_input: { command: `GH_X=1 gh pr create --body-file "${bodyFile}"` } };
  const prefixed = { tool_name: 'Bash', tool_input: { command: `if true; then /usr/bin/git commit -m "${TRAILER}"; fi` } };
  expect(run(['claude-hook'], JSON.stringify(viaFile)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(prefixed)).status).toBe(2);
  const clean = { tool_name: 'mcp__github__create_pull_request', tool_input: { body: 'Done' } };
  expect(run(['claude-hook'], JSON.stringify(pr)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(commit)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(search)).status).toBe(0);
  expect(run(['claude-hook'], JSON.stringify(clean)).status).toBe(0);
});

test('Claude Code hook guards PowerShell commands like Bash', () => {
  const ps = { tool_name: 'PowerShell', tool_input: { command: `git commit -m "x ${SESSION}"` } };
  const read = { tool_name: 'PowerShell', tool_input: { command: `Select-String ${HOST}/ *.md` } };
  expect(run(['claude-hook'], JSON.stringify(ps)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(read)).status).toBe(0);
  const settings = JSON.parse(fs.readFileSync(path.join(ROOT, '.claude/settings.json'), 'utf8'));
  expect(settings.hooks.PreToolUse.some((h) => new RegExp(`^(${h.matcher})$`).test('PowerShell'))).toBe(true);
});

test('repo git hooks still run the global hooks that core.hooksPath would hide', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'guard-'));
  const globalHooks = path.join(dir, 'hooks');
  fs.mkdirSync(globalHooks);
  const ran = path.join(dir, 'ran');
  for (const hook of ['commit-msg', 'pre-push']) {
    fs.writeFileSync(path.join(globalHooks, hook), `#!/bin/sh\ncat >/dev/null\necho ${hook} >> "${ran}"\n`, { mode: 0o755 });
  }
  const config = path.join(dir, 'gitconfig');
  fs.writeFileSync(config, `[core]\n\thooksPath = ${globalHooks}\n`);
  const env = { ...process.env, GIT_CONFIG_GLOBAL: config };
  const msg = path.join(dir, 'msg');
  const hook = (name, args, input) =>
    spawnSync(path.join(ROOT, '.githooks', name), args, { cwd: ROOT, env, input, encoding: 'utf8' });
  fs.writeFileSync(msg, 'Fix thing\n');
  expect(hook('commit-msg', [msg], '').status).toBe(0);
  expect(hook('pre-push', ['origin', 'url'], '').status).toBe(0);
  expect(fs.readFileSync(ran, 'utf8').split('\n').filter(Boolean)).toEqual(['commit-msg', 'pre-push']);
  // A rejected message never reaches the global hook
  fs.writeFileSync(msg, `Fix thing\n\n${TRAILER}\n`);
  expect(hook('commit-msg', [msg], '').status).toBe(1);
  expect(fs.readFileSync(ran, 'utf8').split('\n').filter(Boolean)).toHaveLength(2);
});

test('no tracked file links to a Claude session, thread or project', () => {
  const result = run(['check-repo']);
  expect(result.stderr).toBe('');
  expect(result.status).toBe(0);
});

test('hooks are wired up: git hooks path, executable hooks and Claude settings', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  expect(pkg.scripts.prepare).toContain('core.hooksPath .githooks');
  for (const hook of ['commit-msg', 'pre-push']) {
    const mode = execFileSync('git', ['ls-files', '-s', `.githooks/${hook}`], { cwd: ROOT, encoding: 'utf8' });
    expect(mode.startsWith('100755')).toBe(true);
  }
  const settings = JSON.parse(fs.readFileSync(path.join(ROOT, '.claude/settings.json'), 'utf8'));
  const commands = settings.hooks.PreToolUse.flatMap((h) => h.hooks.map((x) => x.command));
  expect(commands.some((c) => c.includes('claude-link-guard.cjs') && c.includes('claude-hook'))).toBe(true);
});
