// Guard that keeps Claude session, thread and project links off GitHub
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync, spawnSync } = require('child_process');
const { findLinks, scrub } = require('../scripts/claude-link-guard.cjs');

const ROOT = path.join(__dirname, '..');
const GUARD = path.join(ROOT, 'scripts/claude-link-guard.cjs');
// Built from parts so this file never contains a real link
const HOST = 'claude' + '.ai';
const SESSION = `https://${HOST}/code/session_0123abc`;
const PROJECT = `https://${HOST}/code/project/chan_1?thread=cmsg_2`;
const TRAILER = 'Claude' + '-Session: ' + SESSION;
const MARKER = '<!-- claude' + '-projects-attribution: {"github_login":"someone"} -->';

function run(args, input) {
  return spawnSync('node', [GUARD, ...args], { cwd: ROOT, input, encoding: 'utf8' });
}

test('detects session, project and bare links, trailers and the attribution marker', () => {
  expect(findLinks(`see ${SESSION}`)).toHaveLength(1);
  expect(findLinks(`[thread](${PROJECT})`)).toHaveLength(1);
  expect(findLinks(`${HOST}/code`)).toHaveLength(1);
  expect(findLinks(`fix\n\n${TRAILER}\n`)).toHaveLength(1);
  expect(findLinks(MARKER)).toHaveLength(1);
  expect(findLinks('Generated with [Claude Code](https://claude.com/claude-code)')).toHaveLength(0);
  expect(findLinks('Co-Authored-By: Claude <noreply@anthropic.com>')).toHaveLength(0);
});

test('scrub removes the attribution block and session lines but keeps the rest', () => {
  const body = [
    MARKER,
    `_Requested by **lazy** · [project thread](${PROJECT})_`,
    '',
    'Before: something. After: something better.',
    '',
    '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
    '',
    SESSION,
    '',
    `[Fix this →](https://${HOST}/code?q=do%20it)`,
    `_Generated by [Claude Code](https://${HOST}/code)_`,
  ].join('\n');
  const clean = scrub(body);
  expect(findLinks(clean)).toHaveLength(0);
  expect(clean).toContain('Before: something. After: something better.');
  expect(clean).toContain('Generated with [Claude Code](https://claude.com/claude-code)');
  expect(clean).toContain('_Generated by Claude Code_');
  expect(clean).not.toContain('Requested by');
  expect(clean).not.toContain('Fix this');
  expect(scrub('nothing to see')).toBe('nothing to see');
});

test('commit-msg check rejects a session trailer and accepts a clean message', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'guard-'));
  const bad = path.join(dir, 'bad');
  const good = path.join(dir, 'good');
  fs.writeFileSync(bad, `Fix thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n${TRAILER}\n`);
  fs.writeFileSync(good, 'Fix thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n');
  expect(run(['check-msg', bad]).status).toBe(1);
  expect(run(['check-msg', good]).status).toBe(0);
});

test('Claude Code hook blocks publishing a link and allows everything else', () => {
  const pr = { tool_name: 'mcp__github__create_pull_request', tool_input: { body: `Done\n\n${SESSION}` } };
  const commit = { tool_name: 'Bash', tool_input: { command: `git commit -m "x\n\n${TRAILER}"` } };
  const push = { tool_name: 'Bash', tool_input: { command: `cd repo && git -C . commit -m "x ${SESSION}"` } };
  const search = { tool_name: 'Bash', tool_input: { command: `grep -r ${HOST}/ .` } };
  expect(run(['claude-hook'], JSON.stringify(push)).status).toBe(2);
  const clean = { tool_name: 'mcp__github__create_pull_request', tool_input: { body: 'Done' } };
  expect(run(['claude-hook'], JSON.stringify(pr)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(commit)).status).toBe(2);
  expect(run(['claude-hook'], JSON.stringify(search)).status).toBe(0);
  expect(run(['claude-hook'], JSON.stringify(clean)).status).toBe(0);
});

test('no tracked file links to a Claude session, thread or project', () => {
  const result = run(['check-repo']);
  expect(result.stderr).toBe('');
  expect(result.status).toBe(0);
});

test('hooks are wired up: git hooks path, executable hooks and Claude settings', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  expect(pkg.scripts.prepare).toContain('core.hooksPath .githooks');
  for (const hook of ['commit-msg', 'pre-push']) {
    const mode = execFileSync('git', ['ls-files', '-s', `.githooks/${hook}`], { cwd: ROOT, encoding: 'utf8' });
    expect(mode.startsWith('100755')).toBe(true);
  }
  const settings = JSON.parse(fs.readFileSync(path.join(ROOT, '.claude/settings.json'), 'utf8'));
  const commands = settings.hooks.PreToolUse.flatMap((h) => h.hooks.map((x) => x.command));
  expect(commands.some((c) => c.includes('claude-link-guard.cjs') && c.includes('claude-hook'))).toBe(true);
});
